environment_config:
  path: src/gen/config.dart
  class: BotConfig

  fields:
    token:
      config_field: true

    mongo_uri:
      default: mongodb://localhost/dialog_bot

    home_route:
      default: /start

    invite_lifetime:
      default: 14
      type: Duration
      pattern: 'Duration(days: __VALUE__)'

    bot_link:
      default: https://t.me/novy_dialog_dev_bot