name: dialog_bot
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  json_annotation: ^4.5.0
  mongo_dart: ^0.7.4+1
  teledart: ^0.3.4

dev_dependencies:
  build_runner: ^2.1.10
  environment_config: ^3.0.0
  json_serializable: ^6.2.0
  lints: ^2.0.0
