name: dialog_bot
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  bloc: ^8.0.3
  get_it: ^7.2.0
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  logger: ^1.1.0
  meta: ^1.8.0
  mongo_dart: ^0.7.4+1
  teledart: ^0.3.4

dev_dependencies:
  build_runner: ^2.1.11
  environment_config: ^3.0.0
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
  lints: ^2.0.0
  mockito: ^5.2.0
  test: ^1.21.1
